# House Price Prediction

### Business Problem

Accurately predicting house prices is crucial for:
- Real estate companies (pricing strategy)
- Home buyers & sellers (fair valuation)
- Financial institutions (loan risk assessment)

### Objective
Build a machine learning model that predicts **house price** based on:
- Property characteristics
- Location & accessibility
- Amenities
- Socio-economic factors

### Type of Problem
- Supervised Learning
- Regression problem

### Target Variable
- `price`

### Evaluation Metrics
- RMSE (Root Mean Squared Error)
- MAE (Mean Absolute Error)

# Load Dataset

In [2]:
import pandas as pd

In [3]:
ds = pd.read_csv('../data/house_price_raw_data.csv')

In [4]:
ds

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price
0,1360,6,2,2,9,10,0,0,1,0,1,0,1,0,6.939333,7242,premium,low,5.952493e+05
1,4272,5,2,3,24,8,1,0,0,1,1,1,1,0,0.400918,7729,low,low,1.571208e+06
2,3592,1,4,3,4,20,0,1,1,1,0,1,0,1,6.292386,1081,premium,mid,1.379943e+06
3,966,5,2,2,6,14,1,0,0,0,0,1,1,0,8.964112,8912,medium,low,4.367819e+05
4,4926,4,3,1,18,9,0,0,0,0,1,0,1,1,2.843309,8146,low,mid,1.792425e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,733,1,4,1,23,23,0,0,1,0,0,1,1,1,1.699633,2188,premium,mid,3.386262e+05
49996,3420,4,1,3,9,13,1,1,1,0,0,0,1,1,9.451960,7273,low,low,1.185043e+06
49997,2218,3,1,2,3,6,0,1,1,0,1,0,0,1,8.659219,9856,medium,mid,8.443978e+05
49998,992,2,4,3,26,20,1,0,0,0,0,0,1,0,6.343849,2858,premium,low,3.796953e+05
49999,3782,1,2,2,5,13,1,0,0,1,1,1,0,0,5.254151,8465,premium,high,1.450285e+06

In [5]:
# Create column description DataFrame

column_description = {
    "Column Name": [
        "area", "bedrooms", "bathrooms", "floors", "age",
        "distance", "location", "public_transport",
        "garage", "parking", "garden", "security",
        "school_nearby", "hospital_nearby", "shopping_mall_nearby",
        "crime_rate", "population_density", "income_level",
        "price"
    ],
    
    "Description": [
        "Total built-up area of the house in square feet",
        "Number of bedrooms in the house",
        "Number of bathrooms in the house",
        "Number of floors in the building",
        "Age of the property in years",
        "Distance from city center in kilometers",
        "Category of location (low, medium, premium)",
        "Availability of public transport nearby (0 = No, 1 = Yes)",
        "Availability of garage (0 = No, 1 = Yes)",
        "Availability of parking space (0 = No, 1 = Yes)",
        "Presence of a garden (0 = No, 1 = Yes)",
        "Availability of security system (0 = No, 1 = Yes)",
        "School available nearby (0 = No, 1 = Yes)",
        "Hospital available nearby (0 = No, 1 = Yes)",
        "Shopping mall available nearby (0 = No, 1 = Yes)",
        "Crime rate of the area on a scale of 0 to 10",
        "Population density of the area",
        "Income category of residents (low, mid, high)",
        "Target variable representing estimated house price"
    ],
    
    "Data Type": [
        "Numerical", "Numerical", "Numerical", "Numerical", "Numerical",
        "Numerical", "Categorical", "Binary",
        "Binary", "Binary", "Binary", "Binary",
        "Binary", "Binary", "Binary",
        "Numerical", "Numerical", "Categorical",
        "Numerical (Target)"
    ]
}

columns_df = pd.DataFrame(column_description)

columns_df

,Column Name,Description,Data Type
0,area,Total built-up area of the house in square feet,Numerical
1,bedrooms,Number of bedrooms in the house,Numerical
2,bathrooms,Number of bathrooms in the house,Numerical
3,floors,Number of floors in the building,Numerical
4,age,Age of the property in years,Numerical
5,distance,Distance from city center in kilometers,Numerical
6,location,"Category of location (low, medium, premium)",Categorical
7,public_transport,Availability of public transport nearby (0 = N...,Binary
8,garage,"Availability of garage (0 = No, 1 = Yes)",Binary
9,parking,"Availability of parking space (0 = No, 1 = Yes)",Binary
10,garden,"Presence of a garden (0 = No, 1 = Yes)",Binary
11,security,"Availability of security system (0 = No, 1 = Yes)",Binary
12,school_nearby,"School available nearby (0 = No, 1 = Yes)",Binary
13,hospital_nearby,"Hospital available nearby (0 = No, 1 = Yes)",Binary
14,shopping_mall_nearby,"Shopping mall available nearby (0 = No, 1 = Yes)",Binary
15,crime_rate,Crime rate of the area on a scale of 0 to 10,Numerical
16,population_density,Population density of the area,Numerical
17,income_level,"Income category of residents (low, mid, high)",Categorical
18,price,Target variable representing estimated house p...,Numerical (Target)

# Understanding DS

In [6]:
ds.head()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price
0,1360,6,2,2,9,10,0,0,1,0,1,0,1,0,6.939333,7242,premium,low,5.952493e+05
1,4272,5,2,3,24,8,1,0,0,1,1,1,1,0,0.400918,7729,low,low,1.571208e+06
2,3592,1,4,3,4,20,0,1,1,1,0,1,0,1,6.292386,1081,premium,mid,1.379943e+06
3,966,5,2,2,6,14,1,0,0,0,0,1,1,0,8.964112,8912,medium,low,4.367819e+05
4,4926,4,3,1,18,9,0,0,0,0,1,0,1,1,2.843309,8146,low,mid,1.792425e+06

In [7]:
ds.tail()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price
49995,733,1,4,1,23,23,0,0,1,0,0,1,1,1,1.699633,2188,premium,mid,3.386262e+05
49996,3420,4,1,3,9,13,1,1,1,0,0,0,1,1,9.451960,7273,low,low,1.185043e+06
49997,2218,3,1,2,3,6,0,1,1,0,1,0,0,1,8.659219,9856,medium,mid,8.443978e+05
49998,992,2,4,3,26,20,1,0,0,0,0,0,1,0,6.343849,2858,premium,low,3.796953e+05
49999,3782,1,2,2,5,13,1,0,0,1,1,1,0,0,5.254151,8465,premium,high,1.450285e+06

In [8]:
ds.shape

(50000, 19)

In [9]:
ds.shape[0]

50000

In [10]:
ds.shape[1]

19

In [11]:
ds.columns

Index(['area', 'bedrooms', 'bathrooms', 'floors', 'age', 'distance', 'garage',
       'parking', 'garden', 'security', 'school_nearby', 'hospital_nearby',
       'shopping_mall_nearby', 'public_transport', 'crime_rate',
       'population_density', 'location', 'income_level', 'price'],
      dtype='object')

In [12]:
ds.dtypes

area                      int64
bedrooms                  int64
bathrooms                 int64
floors                    int64
age                       int64
distance                  int64
garage                    int64
parking                   int64
garden                    int64
security                  int64
school_nearby             int64
hospital_nearby           int64
shopping_mall_nearby      int64
public_transport          int64
crime_rate              float64
population_density        int64
location                 object
income_level             object
price                   float64
dtype: object

In [13]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   area                  50000 non-null  int64
 1   bedrooms              50000 non-null  int64
 2   bathrooms             50000 non-null  int64
 3   floors                50000 non-null  int64
 4   age                   50000 non-null  int64
 5   distance              50000 non-null  int64
 6   garage                50000 non-null  int64
 7   parking               50000 non-null  int64
 8   garden                50000 non-null  int64
 9   security              50000 non-null  int64
 10  school_nearby         50000 non-null  int64
 11  hospital_nearby       50000 non-null  int64
 12  shopping_mall_nearby  50000 non-null  int64
 13  public_transport      50000 non-null  int64
 14  crime_rate            50000 non-null  float64
 15  population_density    50000 non-null  int64
 16  location              50000 non-null  object
 17  income_level          50000 non-null  object
 18  price                 50000 non-null  float64
dtypes: float64(2), int64(15), object(2)
memory usage: 7.2+ MB

In [14]:
ds.describe()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,price
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,5.000000e+04
mean,2752.970540,3.496040,2.498040,1.997060,19.573740,14.968700,0.500540,0.497300,0.500280,0.496220,0.501100,0.498320,0.498320,0.500040,5.006444,5065.94598,1.030261e+06
std,1297.148134,1.712146,1.117704,0.815368,11.552502,8.363714,0.500005,0.499998,0.500005,0.499991,0.500004,0.500002,0.500002,0.500005,2.876776,2864.34322,4.580199e+05
min,500.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000311,100.00000,9.090069e+04
25%,1630.000000,2.000000,1.000000,1.000000,10.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.523018,2575.00000,6.357375e+05
50%,2756.000000,3.000000,2.000000,2.000000,20.000000,15.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,5.022946,5060.50000,1.031763e+06
75%,3872.000000,5.000000,3.000000,3.000000,30.000000,22.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.479632,7543.00000,1.423102e+06
max,4999.000000,6.000000,4.000000,3.000000,39.000000,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.999869,9999.00000,1.996474e+06

In [15]:
ds.describe(include = 'all')

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000,50000,5.000000e+04
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medium,mid,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16756,16738,NaN
mean,2752.970540,3.496040,2.498040,1.997060,19.573740,14.968700,0.500540,0.497300,0.500280,0.496220,0.501100,0.498320,0.498320,0.500040,5.006444,5065.94598,NaN,NaN,1.030261e+06
std,1297.148134,1.712146,1.117704,0.815368,11.552502,8.363714,0.500005,0.499998,0.500005,0.499991,0.500004,0.500002,0.500002,0.500005,2.876776,2864.34322,NaN,NaN,4.580199e+05
min,500.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000311,100.00000,NaN,NaN,9.090069e+04
25%,1630.000000,2.000000,1.000000,1.000000,10.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.523018,2575.00000,NaN,NaN,6.357375e+05
50%,2756.000000,3.000000,2.000000,2.000000,20.000000,15.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,5.022946,5060.50000,NaN,NaN,1.031763e+06
75%,3872.000000,5.000000,3.000000,3.000000,30.000000,22.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.479632,7543.00000,NaN,NaN,1.423102e+06
max,4999.000000,6.000000,4.000000,3.000000,39.000000,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.999869,9999.00000,NaN,NaN,1.996474e+06

# Cleaning

In [16]:
ds.duplicated().sum()

np.int64(0)

In [17]:
ds.isnull().sum()

area                    0
bedrooms                0
bathrooms               0
floors                  0
age                     0
distance                0
garage                  0
parking                 0
garden                  0
security                0
school_nearby           0
hospital_nearby         0
shopping_mall_nearby    0
public_transport        0
crime_rate              0
population_density      0
location                0
income_level            0
price                   0
dtype: int64

In [18]:
ds.sample(5)

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price
44163,2877,4,3,2,35,9,0,0,0,0,0,0,0,0,9.873286,1241,premium,low,1.040328e+06
29635,3260,1,4,2,16,19,0,0,1,1,1,0,1,0,8.628926,9789,premium,high,1.236228e+06
14988,1919,3,1,3,20,20,0,0,0,0,0,1,1,0,7.470514,9212,low,low,6.247489e+05
24480,3521,1,2,2,21,10,1,1,0,1,1,1,1,0,7.621127,1751,medium,low,1.213264e+06
26665,4306,1,2,2,30,4,1,1,1,1,1,0,0,0,5.133632,3007,premium,mid,1.568536e+06

In [19]:
# Convert price to normal float and round to nearest integer

ds['price_rounded'] = ds['price'].round(0).astype(int)

In [20]:
ds[['price', 'price_rounded']].head()

          price  price_rounded
0  5.952493e+05         595249
1  1.571208e+06        1571208
2  1.379943e+06        1379943
3  4.367819e+05         436782
4  1.792425e+06        1792425

In [21]:
ds['crime_rate'] = ds['crime_rate'].round(2)

In [22]:
ds

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location,income_level,price,price_rounded
0,1360,6,2,2,9,10,0,0,1,0,1,0,1,0,6.94,7242,premium,low,5.952493e+05,595249
1,4272,5,2,3,24,8,1,0,0,1,1,1,1,0,0.40,7729,low,low,1.571208e+06,1571208
2,3592,1,4,3,4,20,0,1,1,1,0,1,0,1,6.29,1081,premium,mid,1.379943e+06,1379943
3,966,5,2,2,6,14,1,0,0,0,0,1,1,0,8.96,8912,medium,low,4.367819e+05,436782
4,4926,4,3,1,18,9,0,0,0,0,1,0,1,1,2.84,8146,low,mid,1.792425e+06,1792425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,733,1,4,1,23,23,0,0,1,0,0,1,1,1,1.70,2188,premium,mid,3.386262e+05,338626
49996,3420,4,1,3,9,13,1,1,1,0,0,0,1,1,9.45,7273,low,low,1.185043e+06,1185043
49997,2218,3,1,2,3,6,0,1,1,0,1,0,0,1,8.66,9856,medium,mid,8.443978e+05,844398
49998,992,2,4,3,26,20,1,0,0,0,0,0,1,0,6.34,2858,premium,low,3.796953e+05,379695
49999,3782,1,2,2,5,13,1,0,0,1,1,1,0,0,5.25,8465,premium,high,1.450285e+06,1450285

In [23]:
ds.loc[ds['price_rounded'].idxmax()]

area                              4903
bedrooms                             6
bathrooms                            4
floors                               3
age                                  0
distance                             6
garage                               0
parking                              1
garden                               0
security                             0
school_nearby                        1
hospital_nearby                      0
shopping_mall_nearby                 0
public_transport                     1
crime_rate                        2.56
population_density                7241
location                       premium
income_level                      high
price                   1996474.394463
price_rounded                  1996474
Name: 8886, dtype: object

# Realistic Price Formula
(Indian Context)

In [24]:
base_price_per_sqft = {
    'low': 3000,
    'medium': 6000,
    'premium': 9000
}

ds['base_price'] = ds['area'] * ds['location'].map(base_price_per_sqft)

# Amenities bonus
ds['amenities_score'] = (
    ds['garage'] + ds['parking'] + ds['garden'] + ds['security']
) * 100000  # ₹1 lakh each

# Distance penalty
ds['distance_penalty'] = ds['distance'] * 20000

# Crime penalty
ds['crime_penalty'] = ds['crime_rate'] * 50000

# Final realistic price
ds['price_realistic'] = (
    ds['base_price']
    + ds['amenities_score']
    - ds['distance_penalty']
    - ds['crime_penalty']
)

ds['price_realistic'] = ds['price_realistic'].clip(lower=500000)

In [25]:
ds.head()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,...,population_density,location,income_level,price,price_rounded,base_price,amenities_score,distance_penalty,crime_penalty,price_realistic
0,1360,6,2,2,9,10,0,0,1,0,...,7242,premium,low,5.952493e+05,595249,12240000,100000,200000,347000.0,11793000.0
1,4272,5,2,3,24,8,1,0,0,1,...,7729,low,low,1.571208e+06,1571208,12816000,200000,160000,20000.0,12836000.0
2,3592,1,4,3,4,20,0,1,1,1,...,1081,premium,mid,1.379943e+06,1379943,32328000,300000,400000,314500.0,31913500.0
3,966,5,2,2,6,14,1,0,0,0,...,8912,medium,low,4.367819e+05,436782,5796000,100000,280000,448000.0,5168000.0
4,4926,4,3,1,18,9,0,0,0,0,...,8146,low,mid,1.792425e+06,1792425,14778000,0,180000,142000.0,14456000.0

While validating synthetic data, I identified unrealistic pricing where large premium houses were undervalued. I redesigned the price-generation logic using real-world per-square-foot pricing, location multipliers, and amenity premiums to align the dataset with actual Indian real estate markets.

| Location | ₹ per sq.ft | Why                      |
| -------- | ----------- | ------------------------ |
| low      | 3,000       | Outskirts, less demand   |
| medium   | 6,000       | Regular city areas       |
| premium  | 9,000       | Posh / high-demand areas |


| Amenity  | Value     |
| -------- | --------- |
| Garage   | ₹1,00,000 |
| Parking  | ₹1,00,000 |
| Garden   | ₹1,00,000 |
| Security | ₹1,00,000 |


###  Distance penalty

ds['distance_penalty'] = ds['distance'] * 20000

Distance = 10 km

Penalty = 10 × 20,000 = ₹2,00,000

###  crime penalty

ds['crime_penalty'] = ds['crime_rate'] * 50000

Crime Rate = 2.5

Penalty = 2.5 × 50,000 = ₹1,25,000

### Final realistic price

Final Price =(Base Area Price)+ (Amenities Bonus)− (Distance Penalty)− (Crime Penalty)


Base Price        = ₹1,08,00,000
Amenities Bonus   = ₹3,00,000
Distance Penalty  = ₹2,00,000
Crime Penalty     = ₹1,25,000

Final Price = ₹1,07,75,000 (~1.08 Cr)


### Minimum Price Safety Rule

It prevents house prices from becoming unrealistically low.

clip(lower=500000) means:

If the house price is less than ₹5,00,000, set it to ₹5,00,000

clip() is a pandas function used to limit values within a range.

Think of it as a price guard.

In [27]:
ds.loc[ds['price_realistic'].idxmax()]

area                              4997
bedrooms                             2
bathrooms                            1
floors                               3
age                                 36
distance                            12
garage                               1
parking                              1
garden                               1
security                             1
school_nearby                        1
hospital_nearby                      0
shopping_mall_nearby                 0
public_transport                     0
crime_rate                        1.23
population_density                8105
location                       premium
income_level                       low
price                   1781379.382462
price_rounded                  1781379
base_price                    44973000
amenities_score                 400000
distance_penalty                240000
crime_penalty                  61500.0
price_realistic             45071500.0
Name: 14912, dtype: object

# Save_File

In [26]:
ds.to_csv('Cleaned_ds.csv', index=False)